### ISSUE TITLE
Hover effects for thumbnails

### ISSUE THREAD

**Issue by notslang** [slang800/bellasurfaces.com#4]
Mentioned in chat, presumably the dimming & info display from the intent theme. However, this causes an issue because the thumbnails are far smaller than the intent theme, so there's no room to display the title of the project.

**Comment by ccsouthard** [comment]
I was fine with the isotope filter as it came. Since this was not something you wanted to do- I went with this.

Then let's make them just have a [white overlay ](https://obeygiant.com/fine-art/) or if bigger you don't agree or just animate to circles if you don't like either. 

 **I think it should say images and not pieces.**

**Comment by notslang** [comment]
I'm pretty sure you asked me to decrease the size of the thumbnails around 5e619bbe... if you want me to make them bigger again I can switch it back. If you actually want the masonry-style layout, we would need to set image sizes that fit together, and that is a ton of extra editing.

**Comment by notslang** [comment]
> I think it should say images and not pieces.

Actually, it gives a count of how many unique portfolio entries are in that category... I can change that to count the images if you wanted
